---
- name: php7-fpm | start application after the /vagrant share has become available
  lineinfile: dest=/etc/init/php7.0-fpm.conf
    regexp='^start on'
    line='start on vagrant-mounted'

- name: php7-fpm | don't hide error logs while in development
  replace: dest=/etc/php/7.0/fpm/php.ini
    regexp='^(display(_startup)?_errors).*'
    replace='\1 = On'
  notify: restart PHP70-FPM
